# The URL the site will be built for
base_url = "https://ajafri2001.github.io/"

title = "ajafri2001"
minify_html = true
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
comments = false
socials = [
              { name = "github", url = "https://github.com/ajafri2001/", icon = "github" },
              {name = "discord", url = "https://discord.com/users/1237543552733544559", icon = "discord" }
          ]
menu = []

mathjax = true
 mathjax_dollar_inline_enable = true

fancy_code = true
theme = "toggle"
toc = true
